name: Build

on:
  push:
    tags: [ "v*" ]

jobs:
  build:
    runs-on: windows-latest
    name: Build
    steps:
    - uses: actions/checkout@v2.4.0

    - name: Install dependencies
      run: |
        choco install autohotkey innosetup --limit-output -y

    - name: Build app
      shell: powershell
      run: |
        & .\build.bat
        & iscc installer.iss

    - name: Create an archive
      working-directory: dist
      run: |
        7z a hibernate-setup.7z hibernate-setup.exe

    - name: Create release
      uses: ncipollo/release-action@v1.10.0
      with:
        artifacts: "dist/hibernate-setup.7z"
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
